#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`

# go one dir up
PROJECT_ROOT=`dirname $SCRIPTPATH`
cd $PROJECT_ROOT

BACKUP_DIR="/backups/<REPLACE:PROJECT_NAME>"
BACKUP_LOG="/backups/<REPLACE:PROJECT_NAME>.log"
BACKUP_ERROR_LOG="/backups/<REPLACE:PROJECT_NAME>.err"

date >> $BACKUP_LOG 2>> $BACKUP_ERROR_LOG
python $PROJECT_DIR/commands/dumpdata.py >> $BACKUP_LOG 2>> $BACKUP_ERROR_LOG
rdiff-backup $PROJECT_DIR $BACKUP_DIR >> $BACKUP_LOG 2>> $BACKUP_ERROR_LOG
